In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("churn.csv")

df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [2]:
df.tail().T

,7038,7039,7040,7041,7042
customerID,6840-RESVB,2234-XADUH,4801-JZAZL,8361-LTMKD,3186-AJIEK
gender,Male,Female,Female,Male,Male
SeniorCitizen,0,0,0,1,0
Partner,Yes,Yes,Yes,Yes,No
Dependents,Yes,Yes,Yes,No,No
tenure,24,72,11,4,66
PhoneService,Yes,Yes,No,Yes,Yes
MultipleLines,Yes,Yes,No phone service,Yes,No
InternetService,DSL,Fiber optic,DSL,Fiber optic,Fiber optic
OnlineSecurity,Yes,No,Yes,No,Yes
OnlineBackup,No,Yes,No,No,No
DeviceProtection,Yes,Yes,No,No,Yes
TechSupport,Yes,No,No,No,Yes
StreamingTV,Yes,Yes,No,No,Yes
StreamingMovies,Yes,Yes,No,No,Yes
Contract,One year,One year,Month-to-month,Month-to-month,Two year
PaperlessBilling,Yes,Yes,Yes,Yes,Yes
PaymentMethod,Mailed check,Credit card (automatic),Electronic check,Mailed check,Bank transfer (automatic)
MonthlyCharges,84.8,103.2,29.6,74.4,105.65
TotalCharges,1990.5,7362.9,346.45,306.6,6844.5
Churn,No,No,No,Yes,No

In [3]:
df.sample(10).T

,2440,2714,903,2676,4793,6899,4000,5887,1400,35
customerID,2171-UDMFD,6838-YAUVY,5285-MVEHD,1872-EBWSC,2284-VFLKH,3926-CUQZX,0420-HLGXF,4316-XCSLJ,7521-YXVZY,6234-RAAPL
gender,Male,Female,Female,Female,Male,Male,Female,Male,Male,Female
SeniorCitizen,0,0,0,0,0,0,1,0,0,0
Partner,Yes,No,Yes,No,Yes,No,No,No,No,Yes
Dependents,Yes,No,No,No,No,No,No,Yes,Yes,Yes
tenure,32,54,56,29,49,1,39,17,3,72
PhoneService,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes
MultipleLines,No,Yes,No,No,No,No,Yes,No,No,Yes
InternetService,No,Fiber optic,Fiber optic,No,Fiber optic,DSL,Fiber optic,DSL,No,Fiber optic
OnlineSecurity,No internet service,No,Yes,No internet service,No,No,No,Yes,No internet service,Yes
OnlineBackup,No internet service,No,Yes,No internet service,No,No,No,No,No internet service,Yes
DeviceProtection,No internet service,Yes,Yes,No internet service,Yes,No,Yes,No,No internet service,No
TechSupport,No internet service,Yes,No,No internet service,Yes,No,No,No,No internet service,Yes
StreamingTV,No internet service,No,Yes,No internet service,Yes,No,Yes,No,No internet service,Yes
StreamingMovies,No internet service,Yes,Yes,No internet service,Yes,No,Yes,No,No internet service,No
Contract,Month-to-month,Two year,One year,One year,One year,Month-to-month,Month-to-month,Month-to-month,Month-to-month,Two year
PaperlessBilling,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,No,No
PaymentMethod,Credit card (automatic),Bank transfer (automatic),Credit card (automatic),Mailed check,Credit card (automatic),Bank transfer (automatic),Electronic check,Mailed check,Mailed check,Bank transfer (automatic)
MonthlyCharges,19.45,95.1,105.6,20.35,99.25,45.1,99.75,50.3,19.95,99.9
TotalCharges,674.55,5064.85,6068.65,617.35,4920.8,45.1,4036.0,846.8,58.3,7251.7
Churn,No,No,No,No,No,Yes,No,No,No,No

In [4]:
print(f"shape: {df.shape}")
print()
print(f"shape: {df.columns.to_list()}")

shape: (7043, 21)

shape: ['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

In [5]:
total_sum = df['TotalCharges'].sum()
print(total_sum)

16056168.7

In [6]:
print(df.isnull().sum())

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [7]:
tenureArray = df['tenure'].to_numpy()

In [8]:
print(f"Max: {tenureArray.max()}\nMin: {tenureArray.min()}\nMean: {tenureArray.mean()}")

Max: 72
Min: 0
Mean: 32.37114865824223

In [9]:
print(f"Average: {df['MonthlyCharges'].mean()}")

Average: 64.76169246059918

In [10]:
print(f"Sum of MonthlyCharges: {df['MonthlyCharges'].sum()}")

Sum of MonthlyCharges: 456116.6

In [11]:
df1 = df.drop(columns=['customerID'])

In [12]:
print(f"Mean of tenure: {df1['tenure'].mean()}")

Mean of tenure: 32.37114865824223

In [13]:
print(f"Number of items: {df1['InternetService'].count()}")

Number of items: 7043

In [14]:
df.loc[0:10, 'TotalCharges']

0       29.85
1     1889.50
2      108.15
3     1840.75
4      151.65
5      820.50
6     1949.40
7      301.90
8     3046.05
9     3487.95
10     587.45
Name: TotalCharges, dtype: float64